package com.lianne.utils.openai.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;

import java.util.List;

/**
 * Represents the response from the OpenAI API for a chat completion request.
 * <p>
 * This class contains the response data returned by the OpenAI model after processing a chat-based request.
 * The response includes a list of choices, each containing a message generated by the model.
 * </p>
 */
@Data
@AllArgsConstructor
public class ChatCompletionResponse {

        /**
         * A list of choices generated by the OpenAI model.
         * <p>
         * Each {@link Choice} object contains a message, which is the model's response based on the provided conversation context.
         * </p>
         */
        @JsonProperty("choices")
        List<Choice> choices;
}
